const teamsData = {
	PESADOS_FC: {
		name: 'PESADOS FC',
		players: [
			'João Abreu',
			'Fábio Costa',
			'Guilherme Fonseca',
			'Ruben Costa',
			'Paulo Martins',
			'João Cardoso',
			'Diogo Jesus',
			'Alexandre Correia',
			'André Gonçalves',
			'Moisés Rodrigues',
			'Rúben Rodrigues',
		],
	},
	CONDOR_FC: {
		name: 'CONDOR FC',
		players: [
			'Rafael Donati',
			'Bruno Ferreira',
			'Cabiete Mena',
			'Claudio Pintos',
			'Paulo Rocha',
			'Diego Faracini',
			'Alysson Moraes',
			'Henrique Sommer',
			'André Pantoja',
			'Natanael Ferreira',
			'Carlos Neto',
			'António Bartolomeu',
		],
	},
	SEM_NOME: {
		name: 'SEM NOME',
		players: [
			'Rafael Rolo',
			'Lucka Coutinho',
			'Abílio Silva',
			'João Ministro',
			'Ricardo Santos',
			'David Oliveira',
			'Diogo Matos',
			'Bruno Ferreira',
			'Simão Ferreira',
			'Renato Marques',
			'João Mafalda',
			'Duarte Santos ',
		],
	},
	INACREDITAVEL: {
		name: 'INACREDITÁVEL FC',
		players: [
			'Eduardo Leal',
			'Martim Santos Leal',
			'Rodrigo Matos',
			'David Moura',
			'Sérgio Almeida',
			'Pedro Loureiro',
			'Alberto Coli',
			'Nicolás Iacovelli',
			'Martim Matos',
			'Gabriel Prates',
			'Fábio Andrade',
		],
	},
	CHIMBARRAO_FC: {
		name: 'CHIMBARRÃO FC',
		players: [
			'Rodrigo Lage',
			'Hugo Simões',
			'Bruno Santos',
			'Bernardo Abadito',
			'Diego Mota',
			'Jorge Marques',
			'Guilherme Neves',
			'Henrique Lopes',
			'Bruno Almeida',
			'Afonso Vilar',
			'Tiago Salgueiro',
			'João Correia',
		],
	},
	VM_CAR_AUTOMOVEIS: {
		name: 'VM CAR AUTOMÓVEIS',
		players: [
			'Gonçalo Sousa',
			'Francisco Cruz',
			'Sebastião Henriques',
			'Hernani Manuel',
			'Pedro Pratas',
			'Pedro Santos',
			'Henrique Pereira',
			'José Ferreira',
			'Daniel Lopes',
			'Rodrigo Cardoso',
			'André Guilherme',
			'Bruno Almeida',
		],
	},
	RO_SERRALHARIA: {
		name: 'RO SERRALHARIA',
		players: [
			'Francisco Simões',
			'Tiago Marques',
			'Gonçalo Silva',
			'Rui Marques',
			'André Lopes',
			'Gonçalo Coelho',
			'Diogo Matos',
			'João Martins',
			'Hugo Tavares',
			'Guilherme Oliveira',
			'Rui Matos',
			'Ricardo Oliveira',
		],
	},
	MEGATEC: {
		name: 'MEGATEC',
		players: [],
	},
	FUT_SEGUNDA_FEIRA_CA_SE_BICA: {
		name: 'FUT SEGUNDA CÁ SE BICA',
		players: [],
	},
	BISTAS: {
		name: 'BISTAS',
		players: [],
	},
};

module.exports = { teamsData };
