services:
  certbot:
      image: certbot/certbot:latest
      command: >-
              certonly --reinstall --webroot --webroot-path=/var/www/certbot --email juvenildelordosa@gmail.com --agree-tos --no-eff-email -d ajlordosa.pt -d torneio.ajlordosa.pt torneiotemp.ajlordosa.pt
      volumes:
          - ./certbot/www/:/var/www/certbot/:rw
          - ./certbot/conf/:/etc/letsencrypt/:rw